import random

# Generate a random number between 1 and 100
random_number = random.randint(1, 100)

# Initialize the number of guesses
num_guesses = 0

# Use a while loop to keep asking the user for guesses until they guess the correct number
while True:
    # Ask the user to input a number
    guess = int(input("Guess a number between 1 and 100: "))
    
    # Check if the number is equal to the random number generated by the computer
    if guess == random_number:
        num_guesses += 1
        print(f"Congratulations! You guessed the number in {num_guesses} guesses.")
        break
    
    # If the number is not equal to the random number, check if it is higher or lower than the random number and print a message accordingly
    elif guess < random_number:
        num_guesses += 1
        print("Too low! Guess again.")
    else:
        num_guesses += 1
        print("Too high! Guess again.")
